# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'utama.ui'
#
# Created: Sat Mar 18 03:01:39 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(832, 863)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.groupBoxTunai = QtGui.QGroupBox(self.tab)
        self.groupBoxTunai.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxTunai.setObjectName(_fromUtf8("groupBoxTunai"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBoxTunai)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_20 = QtGui.QLabel(self.groupBoxTunai)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_6.addWidget(self.label_20, 0, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem, 0, 9, 1, 1)
        self.label_86 = QtGui.QLabel(self.groupBoxTunai)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_86.setFont(font)
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName(_fromUtf8("label_86"))
        self.gridLayout_6.addWidget(self.label_86, 0, 6, 1, 3)
        self.lineEdit100k = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEdit100k.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit100k.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit100k.setObjectName(_fromUtf8("lineEdit100k"))
        self.gridLayout_6.addWidget(self.lineEdit100k, 1, 1, 1, 1)
        self.label_75 = QtGui.QLabel(self.groupBoxTunai)
        self.label_75.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.gridLayout_6.addWidget(self.label_75, 2, 3, 1, 1)
        self.lineEditTas1 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTas1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTas1.setObjectName(_fromUtf8("lineEditTas1"))
        self.gridLayout_6.addWidget(self.lineEditTas1, 2, 6, 1, 1)
        self.lineEditTot100k = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTot100k.setEnabled(False)
        self.lineEditTot100k.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTot100k.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTot100k.setObjectName(_fromUtf8("lineEditTot100k"))
        self.gridLayout_6.addWidget(self.lineEditTot100k, 1, 2, 1, 1)
        self.lineEditSegel1 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditSegel1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditSegel1.setObjectName(_fromUtf8("lineEditSegel1"))
        self.gridLayout_6.addWidget(self.lineEditSegel1, 2, 7, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBoxTunai)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_6.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_85 = QtGui.QLabel(self.groupBoxTunai)
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName(_fromUtf8("label_85"))
        self.gridLayout_6.addWidget(self.label_85, 1, 8, 1, 1)
        self.label_74 = QtGui.QLabel(self.groupBoxTunai)
        self.label_74.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.gridLayout_6.addWidget(self.label_74, 1, 3, 1, 1)
        self.label_76 = QtGui.QLabel(self.groupBoxTunai)
        self.label_76.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.gridLayout_6.addWidget(self.label_76, 3, 3, 1, 1)
        self.label_67 = QtGui.QLabel(self.groupBoxTunai)
        self.label_67.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.gridLayout_6.addWidget(self.label_67, 2, 0, 1, 1)
        self.label_68 = QtGui.QLabel(self.groupBoxTunai)
        self.label_68.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.gridLayout_6.addWidget(self.label_68, 3, 0, 1, 1)
        self.label_82 = QtGui.QLabel(self.groupBoxTunai)
        self.label_82.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.gridLayout_6.addWidget(self.label_82, 9, 0, 1, 2)
        self.label_69 = QtGui.QLabel(self.groupBoxTunai)
        self.label_69.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.gridLayout_6.addWidget(self.label_69, 4, 0, 1, 1)
        self.label_70 = QtGui.QLabel(self.groupBoxTunai)
        self.label_70.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.gridLayout_6.addWidget(self.label_70, 5, 0, 1, 1)
        self.label_73 = QtGui.QLabel(self.groupBoxTunai)
        self.label_73.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout_6.addWidget(self.label_73, 8, 0, 1, 1)
        self.lineEditTot1k = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTot1k.setEnabled(False)
        self.lineEditTot1k.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTot1k.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTot1k.setObjectName(_fromUtf8("lineEditTot1k"))
        self.gridLayout_6.addWidget(self.lineEditTot1k, 7, 2, 1, 1)
        self.lineEditTot2k = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTot2k.setEnabled(False)
        self.lineEditTot2k.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTot2k.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTot2k.setObjectName(_fromUtf8("lineEditTot2k"))
        self.gridLayout_6.addWidget(self.lineEditTot2k, 6, 2, 1, 1)
        self.lineEditTot5k = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTot5k.setEnabled(False)
        self.lineEditTot5k.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTot5k.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTot5k.setObjectName(_fromUtf8("lineEditTot5k"))
        self.gridLayout_6.addWidget(self.lineEditTot5k, 5, 2, 1, 1)
        self.lineEditTot10k = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTot10k.setEnabled(False)
        self.lineEditTot10k.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTot10k.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTot10k.setObjectName(_fromUtf8("lineEditTot10k"))
        self.gridLayout_6.addWidget(self.lineEditTot10k, 4, 2, 1, 1)
        self.lineEditTot20k = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTot20k.setEnabled(False)
        self.lineEditTot20k.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTot20k.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTot20k.setObjectName(_fromUtf8("lineEditTot20k"))
        self.gridLayout_6.addWidget(self.lineEditTot20k, 3, 2, 1, 1)
        self.lineEditTot50k = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTot50k.setEnabled(False)
        self.lineEditTot50k.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTot50k.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTot50k.setObjectName(_fromUtf8("lineEditTot50k"))
        self.gridLayout_6.addWidget(self.lineEditTot50k, 2, 2, 1, 1)
        self.lineEdit1k = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEdit1k.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit1k.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit1k.setObjectName(_fromUtf8("lineEdit1k"))
        self.gridLayout_6.addWidget(self.lineEdit1k, 7, 1, 1, 1)
        self.lineEdit2k = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEdit2k.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit2k.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit2k.setObjectName(_fromUtf8("lineEdit2k"))
        self.gridLayout_6.addWidget(self.lineEdit2k, 6, 1, 1, 1)
        self.lineEdit5k = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEdit5k.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit5k.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit5k.setObjectName(_fromUtf8("lineEdit5k"))
        self.gridLayout_6.addWidget(self.lineEdit5k, 5, 1, 1, 1)
        self.lineEdit10k = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEdit10k.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit10k.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit10k.setObjectName(_fromUtf8("lineEdit10k"))
        self.gridLayout_6.addWidget(self.lineEdit10k, 4, 1, 1, 1)
        self.lineEdit20k = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEdit20k.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit20k.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit20k.setObjectName(_fromUtf8("lineEdit20k"))
        self.gridLayout_6.addWidget(self.lineEdit20k, 3, 1, 1, 1)
        self.lineEdit50k = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEdit50k.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit50k.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit50k.setObjectName(_fromUtf8("lineEdit50k"))
        self.gridLayout_6.addWidget(self.lineEdit50k, 2, 1, 1, 1)
        self.label_72 = QtGui.QLabel(self.groupBoxTunai)
        self.label_72.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.gridLayout_6.addWidget(self.label_72, 7, 0, 1, 1)
        self.label_71 = QtGui.QLabel(self.groupBoxTunai)
        self.label_71.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.gridLayout_6.addWidget(self.label_71, 6, 0, 1, 1)
        self.label_77 = QtGui.QLabel(self.groupBoxTunai)
        self.label_77.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.gridLayout_6.addWidget(self.label_77, 4, 3, 1, 1)
        self.label_78 = QtGui.QLabel(self.groupBoxTunai)
        self.label_78.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.gridLayout_6.addWidget(self.label_78, 5, 3, 1, 1)
        self.label_79 = QtGui.QLabel(self.groupBoxTunai)
        self.label_79.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.gridLayout_6.addWidget(self.label_79, 6, 3, 1, 1)
        self.label_81 = QtGui.QLabel(self.groupBoxTunai)
        self.label_81.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.gridLayout_6.addWidget(self.label_81, 8, 3, 1, 1)
        self.lineEditKoin1000 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditKoin1000.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditKoin1000.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditKoin1000.setObjectName(_fromUtf8("lineEditKoin1000"))
        self.gridLayout_6.addWidget(self.lineEditKoin1000, 1, 4, 1, 1)
        self.lineEditKoin500 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditKoin500.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditKoin500.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditKoin500.setObjectName(_fromUtf8("lineEditKoin500"))
        self.gridLayout_6.addWidget(self.lineEditKoin500, 2, 4, 1, 1)
        self.lineEditKoin200 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditKoin200.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditKoin200.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditKoin200.setObjectName(_fromUtf8("lineEditKoin200"))
        self.gridLayout_6.addWidget(self.lineEditKoin200, 3, 4, 1, 1)
        self.lineEditKoin100 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditKoin100.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditKoin100.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditKoin100.setObjectName(_fromUtf8("lineEditKoin100"))
        self.gridLayout_6.addWidget(self.lineEditKoin100, 4, 4, 1, 1)
        self.lineEditKoin50 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditKoin50.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditKoin50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditKoin50.setObjectName(_fromUtf8("lineEditKoin50"))
        self.gridLayout_6.addWidget(self.lineEditKoin50, 5, 4, 1, 1)
        self.lineEditKoin25 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditKoin25.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditKoin25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditKoin25.setObjectName(_fromUtf8("lineEditKoin25"))
        self.gridLayout_6.addWidget(self.lineEditKoin25, 6, 4, 1, 1)
        self.lineEditTotKoin1k = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTotKoin1k.setEnabled(False)
        self.lineEditTotKoin1k.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTotKoin1k.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTotKoin1k.setObjectName(_fromUtf8("lineEditTotKoin1k"))
        self.gridLayout_6.addWidget(self.lineEditTotKoin1k, 1, 5, 1, 1)
        self.lineEditTotKoin500 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTotKoin500.setEnabled(False)
        self.lineEditTotKoin500.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTotKoin500.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTotKoin500.setObjectName(_fromUtf8("lineEditTotKoin500"))
        self.gridLayout_6.addWidget(self.lineEditTotKoin500, 2, 5, 1, 1)
        self.lineEditTotKoin200 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTotKoin200.setEnabled(False)
        self.lineEditTotKoin200.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTotKoin200.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTotKoin200.setObjectName(_fromUtf8("lineEditTotKoin200"))
        self.gridLayout_6.addWidget(self.lineEditTotKoin200, 3, 5, 1, 1)
        self.lineEditTotKoin100 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTotKoin100.setEnabled(False)
        self.lineEditTotKoin100.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTotKoin100.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTotKoin100.setObjectName(_fromUtf8("lineEditTotKoin100"))
        self.gridLayout_6.addWidget(self.lineEditTotKoin100, 4, 5, 1, 1)
        self.lineEditTotKoin50 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTotKoin50.setEnabled(False)
        self.lineEditTotKoin50.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTotKoin50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTotKoin50.setObjectName(_fromUtf8("lineEditTotKoin50"))
        self.gridLayout_6.addWidget(self.lineEditTotKoin50, 5, 5, 1, 1)
        self.lineEditTotKoin25 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTotKoin25.setEnabled(False)
        self.lineEditTotKoin25.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTotKoin25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTotKoin25.setObjectName(_fromUtf8("lineEditTotKoin25"))
        self.gridLayout_6.addWidget(self.lineEditTotKoin25, 6, 5, 1, 1)
        self.label_80 = QtGui.QLabel(self.groupBoxTunai)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_80.setFont(font)
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.gridLayout_6.addWidget(self.label_80, 0, 3, 1, 3)
        self.label_83 = QtGui.QLabel(self.groupBoxTunai)
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName(_fromUtf8("label_83"))
        self.gridLayout_6.addWidget(self.label_83, 1, 6, 1, 1)
        self.label_84 = QtGui.QLabel(self.groupBoxTunai)
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName(_fromUtf8("label_84"))
        self.gridLayout_6.addWidget(self.label_84, 1, 7, 1, 1)
        self.lineEditSticker1 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditSticker1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditSticker1.setObjectName(_fromUtf8("lineEditSticker1"))
        self.gridLayout_6.addWidget(self.lineEditSticker1, 2, 8, 1, 1)
        self.lineEditGrandTotal = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditGrandTotal.setEnabled(False)
        self.lineEditGrandTotal.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditGrandTotal.setObjectName(_fromUtf8("lineEditGrandTotal"))
        self.gridLayout_6.addWidget(self.lineEditGrandTotal, 9, 2, 1, 4)
        self.label_87 = QtGui.QLabel(self.groupBoxTunai)
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setObjectName(_fromUtf8("label_87"))
        self.gridLayout_6.addWidget(self.label_87, 8, 6, 1, 1)
        self.lineEditCatatan = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditCatatan.setObjectName(_fromUtf8("lineEditCatatan"))
        self.gridLayout_6.addWidget(self.lineEditCatatan, 9, 6, 1, 3)
        self.lineEditTas2 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTas2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTas2.setObjectName(_fromUtf8("lineEditTas2"))
        self.gridLayout_6.addWidget(self.lineEditTas2, 3, 6, 1, 1)
        self.lineEditTas3 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTas3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTas3.setObjectName(_fromUtf8("lineEditTas3"))
        self.gridLayout_6.addWidget(self.lineEditTas3, 4, 6, 1, 1)
        self.lineEditTas4 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTas4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTas4.setObjectName(_fromUtf8("lineEditTas4"))
        self.gridLayout_6.addWidget(self.lineEditTas4, 5, 6, 1, 1)
        self.lineEditTas5 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTas5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditTas5.setObjectName(_fromUtf8("lineEditTas5"))
        self.gridLayout_6.addWidget(self.lineEditTas5, 6, 6, 1, 1)
        self.lineEditSegel2 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditSegel2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditSegel2.setObjectName(_fromUtf8("lineEditSegel2"))
        self.gridLayout_6.addWidget(self.lineEditSegel2, 3, 7, 1, 1)
        self.lineEditSegel3 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditSegel3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditSegel3.setObjectName(_fromUtf8("lineEditSegel3"))
        self.gridLayout_6.addWidget(self.lineEditSegel3, 4, 7, 1, 1)
        self.lineEditSegel4 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditSegel4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditSegel4.setObjectName(_fromUtf8("lineEditSegel4"))
        self.gridLayout_6.addWidget(self.lineEditSegel4, 5, 7, 1, 1)
        self.lineEditSegel5 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditSegel5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditSegel5.setObjectName(_fromUtf8("lineEditSegel5"))
        self.gridLayout_6.addWidget(self.lineEditSegel5, 6, 7, 1, 1)
        self.lineEditSticker2 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditSticker2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditSticker2.setObjectName(_fromUtf8("lineEditSticker2"))
        self.gridLayout_6.addWidget(self.lineEditSticker2, 3, 8, 1, 1)
        self.lineEditSticker3 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditSticker3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditSticker3.setObjectName(_fromUtf8("lineEditSticker3"))
        self.gridLayout_6.addWidget(self.lineEditSticker3, 4, 8, 1, 1)
        self.lineEditSticker4 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditSticker4.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditSticker4.setObjectName(_fromUtf8("lineEditSticker4"))
        self.gridLayout_6.addWidget(self.lineEditSticker4, 5, 8, 1, 1)
        self.lineEditSticker5 = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditSticker5.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditSticker5.setObjectName(_fromUtf8("lineEditSticker5"))
        self.gridLayout_6.addWidget(self.lineEditSticker5, 6, 8, 1, 1)
        self.lineEditTotKertasValue = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTotKertasValue.setEnabled(False)
        self.lineEditTotKertasValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTotKertasValue.setObjectName(_fromUtf8("lineEditTotKertasValue"))
        self.gridLayout_6.addWidget(self.lineEditTotKertasValue, 8, 1, 1, 2)
        self.lineEditTotKoinValue = QtGui.QLineEdit(self.groupBoxTunai)
        self.lineEditTotKoinValue.setEnabled(False)
        self.lineEditTotKoinValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTotKoinValue.setObjectName(_fromUtf8("lineEditTotKoinValue"))
        self.gridLayout_6.addWidget(self.lineEditTotKoinValue, 8, 4, 1, 2)
        self.gridLayout_10.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBoxTunai, 5, 0, 1, 2)
        self.groupBoxGiro = QtGui.QGroupBox(self.tab)
        self.groupBoxGiro.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxGiro.setObjectName(_fromUtf8("groupBoxGiro"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBoxGiro)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_31 = QtGui.QLabel(self.groupBoxGiro)
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_11.addWidget(self.label_31, 0, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.groupBoxGiro)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_11.addWidget(self.label_35, 4, 0, 1, 1)
        self.dateEditTglJtTempo = QtGui.QDateEdit(self.groupBoxGiro)
        self.dateEditTglJtTempo.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dateEditTglJtTempo.setCalendarPopup(True)
        self.dateEditTglJtTempo.setObjectName(_fromUtf8("dateEditTglJtTempo"))
        self.gridLayout_11.addWidget(self.dateEditTglJtTempo, 4, 1, 1, 1)
        self.groupBoxGiroBanyak = QtGui.QGroupBox(self.groupBoxGiro)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBoxGiroBanyak.setFont(font)
        self.groupBoxGiroBanyak.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxGiroBanyak.setFlat(False)
        self.groupBoxGiroBanyak.setCheckable(False)
        self.groupBoxGiroBanyak.setObjectName(_fromUtf8("groupBoxGiroBanyak"))
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBoxGiroBanyak)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.labelSumberDana = QtGui.QLabel(self.groupBoxGiroBanyak)
        self.labelSumberDana.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSumberDana.setObjectName(_fromUtf8("labelSumberDana"))
        self.gridLayout_17.addWidget(self.labelSumberDana, 2, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.groupBoxGiroBanyak)
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_17.addWidget(self.label_36, 0, 0, 1, 1)
        self.lineEditTujuanTrans = QtGui.QLineEdit(self.groupBoxGiroBanyak)
        self.lineEditTujuanTrans.setObjectName(_fromUtf8("lineEditTujuanTrans"))
        self.gridLayout_17.addWidget(self.lineEditTujuanTrans, 4, 1, 1, 1)
        self.labelTujuanTransaksi = QtGui.QLabel(self.groupBoxGiroBanyak)
        self.labelTujuanTransaksi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTujuanTransaksi.setObjectName(_fromUtf8("labelTujuanTransaksi"))
        self.gridLayout_17.addWidget(self.labelTujuanTransaksi, 4, 0, 1, 1)
        self.label_38 = QtGui.QLabel(self.groupBoxGiroBanyak)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_17.addWidget(self.label_38, 3, 0, 1, 1)
        self.comboBoxTujuanTrans = QtGui.QComboBox(self.groupBoxGiroBanyak)
        self.comboBoxTujuanTrans.setObjectName(_fromUtf8("comboBoxTujuanTrans"))
        self.comboBoxTujuanTrans.addItem(_fromUtf8(""))
        self.comboBoxTujuanTrans.addItem(_fromUtf8(""))
        self.gridLayout_17.addWidget(self.comboBoxTujuanTrans, 3, 1, 1, 1)
        self.comboBoxSumberDana = QtGui.QComboBox(self.groupBoxGiroBanyak)
        self.comboBoxSumberDana.setObjectName(_fromUtf8("comboBoxSumberDana"))
        self.comboBoxSumberDana.addItem(_fromUtf8(""))
        self.comboBoxSumberDana.addItem(_fromUtf8(""))
        self.gridLayout_17.addWidget(self.comboBoxSumberDana, 0, 1, 1, 1)
        self.lineEditSumberDana = QtGui.QLineEdit(self.groupBoxGiroBanyak)
        self.lineEditSumberDana.setObjectName(_fromUtf8("lineEditSumberDana"))
        self.gridLayout_17.addWidget(self.lineEditSumberDana, 2, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_17, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBoxGiroBanyak, 5, 0, 1, 2)
        self.label_33 = QtGui.QLabel(self.groupBoxGiro)
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_11.addWidget(self.label_33, 2, 0, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBoxGiro)
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_11.addWidget(self.label_34, 3, 0, 1, 1)
        self.lineEditNomorGiro = QtGui.QLineEdit(self.groupBoxGiro)
        self.lineEditNomorGiro.setObjectName(_fromUtf8("lineEditNomorGiro"))
        self.gridLayout_11.addWidget(self.lineEditNomorGiro, 2, 1, 1, 1)
        self.label_32 = QtGui.QLabel(self.groupBoxGiro)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_11.addWidget(self.label_32, 1, 0, 1, 1)
        self.comboBoxBerita = QtGui.QComboBox(self.groupBoxGiro)
        self.comboBoxBerita.setEditable(True)
        self.comboBoxBerita.setObjectName(_fromUtf8("comboBoxBerita"))
        self.gridLayout_11.addWidget(self.comboBoxBerita, 0, 1, 1, 1)
        self.comboBoxKodeBank = QtGui.QComboBox(self.groupBoxGiro)
        self.comboBoxKodeBank.setEditable(True)
        self.comboBoxKodeBank.setObjectName(_fromUtf8("comboBoxKodeBank"))
        self.gridLayout_11.addWidget(self.comboBoxKodeBank, 1, 1, 1, 1)
        self.comboBoxKota = QtGui.QComboBox(self.groupBoxGiro)
        self.comboBoxKota.setEditable(True)
        self.comboBoxKota.setObjectName(_fromUtf8("comboBoxKota"))
        self.gridLayout_11.addWidget(self.comboBoxKota, 3, 1, 1, 1)
        self.gridLayout_12.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBoxGiro, 6, 0, 1, 2)
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_8.addWidget(self.label_16, 0, 0, 1, 1)
        self.lineEditTerbilang = QtGui.QLineEdit(self.tab)
        self.lineEditTerbilang.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.lineEditTerbilang.setFont(font)
        self.lineEditTerbilang.setObjectName(_fromUtf8("lineEditTerbilang"))
        self.gridLayout_8.addWidget(self.lineEditTerbilang, 3, 0, 1, 2)
        self.gridLayout_14 = QtGui.QGridLayout()
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.pushButtonSimpan = QtGui.QPushButton(self.tab)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/DESIGN/icon/32x32/disk.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSimpan.setIcon(icon)
        self.pushButtonSimpan.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonSimpan.setObjectName(_fromUtf8("pushButtonSimpan"))
        self.gridLayout_14.addWidget(self.pushButtonSimpan, 0, 0, 1, 1)
        self.pushButtonCetak = QtGui.QPushButton(self.tab)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/DESIGN/icon/32x32/printer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCetak.setIcon(icon1)
        self.pushButtonCetak.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonCetak.setObjectName(_fromUtf8("pushButtonCetak"))
        self.gridLayout_14.addWidget(self.pushButtonCetak, 0, 1, 1, 1)
        self.pushButtonBatal = QtGui.QPushButton(self.tab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/DESIGN/icon/32x32/cancel.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonBatal.setIcon(icon2)
        self.pushButtonBatal.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonBatal.setObjectName(_fromUtf8("pushButtonBatal"))
        self.gridLayout_14.addWidget(self.pushButtonBatal, 0, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_14, 7, 0, 1, 1)
        self.gridLayout_20 = QtGui.QGridLayout()
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.comboBoxCekOpik = QtGui.QComboBox(self.tab)
        self.comboBoxCekOpik.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBoxCekOpik.setObjectName(_fromUtf8("comboBoxCekOpik"))
        self.gridLayout_20.addWidget(self.comboBoxCekOpik, 0, 0, 1, 1)
        self.lineEditID = QtGui.QLineEdit(self.tab)
        self.lineEditID.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEditID.setObjectName(_fromUtf8("lineEditID"))
        self.gridLayout_20.addWidget(self.lineEditID, 0, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_20.addWidget(self.label_7, 0, 1, 1, 1)
        self.dateEditTglSetor = QtGui.QDateEdit(self.tab)
        self.dateEditTglSetor.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dateEditTglSetor.setCalendarPopup(True)
        self.dateEditTglSetor.setObjectName(_fromUtf8("dateEditTglSetor"))
        self.gridLayout_20.addWidget(self.dateEditTglSetor, 0, 3, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_20, 0, 1, 1, 1)
        self.gridLayout_35 = QtGui.QGridLayout()
        self.gridLayout_35.setObjectName(_fromUtf8("gridLayout_35"))
        self.lineEditJumlah = QtGui.QLineEdit(self.tab)
        self.lineEditJumlah.setObjectName(_fromUtf8("lineEditJumlah"))
        self.gridLayout_35.addWidget(self.lineEditJumlah, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_35, 2, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_8.addWidget(self.label_17, 2, 0, 1, 1)
        self.comboBoxJenisSetoran = QtGui.QComboBox(self.tab)
        self.comboBoxJenisSetoran.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBoxJenisSetoran.setObjectName(_fromUtf8("comboBoxJenisSetoran"))
        self.comboBoxJenisSetoran.addItem(_fromUtf8(""))
        self.comboBoxJenisSetoran.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.comboBoxJenisSetoran, 4, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_8.addWidget(self.label_18, 4, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem2, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_13.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEditCari = QtGui.QLineEdit(self.tab_3)
        self.lineEditCari.setObjectName(_fromUtf8("lineEditCari"))
        self.gridLayout_13.addWidget(self.lineEditCari, 1, 1, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.tab_3)
        self.tableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_13.addWidget(self.tableWidget, 0, 0, 1, 2)
        self.gridLayout_15.addLayout(self.gridLayout_13, 1, 0, 1, 1)
        self.pushButtonRefresh = QtGui.QPushButton(self.tab_3)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/DESIGN/icon/32x32/arrow_refresh.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRefresh.setIcon(icon3)
        self.pushButtonRefresh.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonRefresh.setObjectName(_fromUtf8("pushButtonRefresh"))
        self.gridLayout_15.addWidget(self.pushButtonRefresh, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.tab_2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 4, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEditRekPelunasan = QtGui.QLineEdit(self.tab_2)
        self.lineEditRekPelunasan.setObjectName(_fromUtf8("lineEditRekPelunasan"))
        self.gridLayout_3.addWidget(self.lineEditRekPelunasan, 6, 1, 1, 1)
        self.lineEditRekGiro = QtGui.QLineEdit(self.tab_2)
        self.lineEditRekGiro.setObjectName(_fromUtf8("lineEditRekGiro"))
        self.gridLayout_3.addWidget(self.lineEditRekGiro, 4, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab_2)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 6, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_2)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 5, 0, 1, 1)
        self.lineEditRekPenjualan = QtGui.QLineEdit(self.tab_2)
        self.lineEditRekPenjualan.setObjectName(_fromUtf8("lineEditRekPenjualan"))
        self.gridLayout_3.addWidget(self.lineEditRekPenjualan, 5, 1, 1, 1)
        self.lineEditNmPemilik = QtGui.QLineEdit(self.tab_2)
        self.lineEditNmPemilik.setObjectName(_fromUtf8("lineEditNmPemilik"))
        self.gridLayout_3.addWidget(self.lineEditNmPemilik, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 11, 0, 1, 1)
        self.lineEditRekPemilik = QtGui.QLineEdit(self.tab_2)
        self.lineEditRekPemilik.setObjectName(_fromUtf8("lineEditRekPemilik"))
        self.gridLayout_3.addWidget(self.lineEditRekPemilik, 3, 1, 1, 1)
        self.comboBoxListPrinter = QtGui.QComboBox(self.tab_2)
        self.comboBoxListPrinter.setObjectName(_fromUtf8("comboBoxListPrinter"))
        self.gridLayout_3.addWidget(self.comboBoxListPrinter, 11, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_7.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_7.addWidget(self.label_13, 4, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_7.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEditNoRek1 = QtGui.QLineEdit(self.tab_2)
        self.lineEditNoRek1.setObjectName(_fromUtf8("lineEditNoRek1"))
        self.gridLayout_7.addWidget(self.lineEditNoRek1, 4, 1, 1, 1)
        self.lineEditTelp1 = QtGui.QLineEdit(self.tab_2)
        self.lineEditTelp1.setObjectName(_fromUtf8("lineEditTelp1"))
        self.gridLayout_7.addWidget(self.lineEditTelp1, 3, 1, 1, 1)
        self.lineEditNm1 = QtGui.QLineEdit(self.tab_2)
        self.lineEditNm1.setObjectName(_fromUtf8("lineEditNm1"))
        self.gridLayout_7.addWidget(self.lineEditNm1, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_7.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_7.addWidget(self.label_14, 0, 0, 1, 1)
        self.lineEditTelp2 = QtGui.QLineEdit(self.tab_2)
        self.lineEditTelp2.setObjectName(_fromUtf8("lineEditTelp2"))
        self.gridLayout_7.addWidget(self.lineEditTelp2, 3, 3, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_2)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_7.addWidget(self.label_25, 3, 2, 1, 1)
        self.lineEditNoRek2 = QtGui.QLineEdit(self.tab_2)
        self.lineEditNoRek2.setObjectName(_fromUtf8("lineEditNoRek2"))
        self.gridLayout_7.addWidget(self.lineEditNoRek2, 4, 3, 1, 1)
        self.label_30 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_7.addWidget(self.label_30, 0, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.tab_2)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_7.addWidget(self.label_26, 4, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.tab_2)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_7.addWidget(self.label_29, 1, 2, 1, 1)
        self.lineEditNm2 = QtGui.QLineEdit(self.tab_2)
        self.lineEditNm2.setObjectName(_fromUtf8("lineEditNm2"))
        self.gridLayout_7.addWidget(self.lineEditNm2, 1, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_7.addWidget(self.label_15, 2, 2, 1, 1)
        self.lineEditAlamat2 = QtGui.QLineEdit(self.tab_2)
        self.lineEditAlamat2.setObjectName(_fromUtf8("lineEditAlamat2"))
        self.gridLayout_7.addWidget(self.lineEditAlamat2, 2, 3, 1, 1)
        self.lineEditAlamat1 = QtGui.QLineEdit(self.tab_2)
        self.lineEditAlamat1.setObjectName(_fromUtf8("lineEditAlamat1"))
        self.gridLayout_7.addWidget(self.lineEditAlamat1, 2, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_5, 10, 0, 1, 2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 13, 0, 1, 1)
        self.pushButtonSimpanInformasi = QtGui.QPushButton(self.tab_2)
        self.pushButtonSimpanInformasi.setIcon(icon)
        self.pushButtonSimpanInformasi.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonSimpanInformasi.setObjectName(_fromUtf8("pushButtonSimpanInformasi"))
        self.gridLayout_3.addWidget(self.pushButtonSimpanInformasi, 12, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEditAlamatPemilik = QtGui.QLineEdit(self.tab_2)
        self.lineEditAlamatPemilik.setObjectName(_fromUtf8("lineEditAlamatPemilik"))
        self.gridLayout_3.addWidget(self.lineEditAlamatPemilik, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.lineEditTelpPemilik = QtGui.QLineEdit(self.tab_2)
        self.lineEditTelpPemilik.setObjectName(_fromUtf8("lineEditTelpPemilik"))
        self.gridLayout_3.addWidget(self.lineEditTelpPemilik, 2, 1, 1, 1)
        self.label_65 = QtGui.QLabel(self.tab_2)
        self.label_65.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.gridLayout_3.addWidget(self.label_65, 7, 0, 1, 1)
        self.lineEditPengambil = QtGui.QLineEdit(self.tab_2)
        self.lineEditPengambil.setObjectName(_fromUtf8("lineEditPengambil"))
        self.gridLayout_3.addWidget(self.lineEditPengambil, 7, 1, 1, 1)
        self.label_66 = QtGui.QLabel(self.tab_2)
        self.label_66.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.gridLayout_3.addWidget(self.label_66, 8, 0, 1, 1)
        self.lineEditAlamatPengambil = QtGui.QLineEdit(self.tab_2)
        self.lineEditAlamatPengambil.setObjectName(_fromUtf8("lineEditAlamatPengambil"))
        self.gridLayout_3.addWidget(self.lineEditAlamatPengambil, 8, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 832, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.comboBoxCekOpik, self.comboBoxJenisSetoran)
        MainWindow.setTabOrder(self.comboBoxJenisSetoran, self.comboBoxBerita)
        MainWindow.setTabOrder(self.comboBoxBerita, self.comboBoxKodeBank)
        MainWindow.setTabOrder(self.comboBoxKodeBank, self.lineEditNomorGiro)
        MainWindow.setTabOrder(self.lineEditNomorGiro, self.comboBoxKota)
        MainWindow.setTabOrder(self.comboBoxKota, self.dateEditTglJtTempo)
        MainWindow.setTabOrder(self.dateEditTglJtTempo, self.comboBoxSumberDana)
        MainWindow.setTabOrder(self.comboBoxSumberDana, self.lineEditSumberDana)
        MainWindow.setTabOrder(self.lineEditSumberDana, self.comboBoxTujuanTrans)
        MainWindow.setTabOrder(self.comboBoxTujuanTrans, self.lineEditTujuanTrans)
        MainWindow.setTabOrder(self.lineEditTujuanTrans, self.pushButtonSimpan)
        MainWindow.setTabOrder(self.pushButtonSimpan, self.pushButtonCetak)
        MainWindow.setTabOrder(self.pushButtonCetak, self.lineEditNmPemilik)
        MainWindow.setTabOrder(self.lineEditNmPemilik, self.lineEditAlamatPemilik)
        MainWindow.setTabOrder(self.lineEditAlamatPemilik, self.lineEditRekPemilik)
        MainWindow.setTabOrder(self.lineEditRekPemilik, self.lineEditRekGiro)
        MainWindow.setTabOrder(self.lineEditRekGiro, self.lineEditRekPenjualan)
        MainWindow.setTabOrder(self.lineEditRekPenjualan, self.lineEditRekPelunasan)
        MainWindow.setTabOrder(self.lineEditRekPelunasan, self.lineEditNm1)
        MainWindow.setTabOrder(self.lineEditNm1, self.lineEditAlamat1)
        MainWindow.setTabOrder(self.lineEditAlamat1, self.lineEditTelp1)
        MainWindow.setTabOrder(self.lineEditTelp1, self.lineEditNoRek1)
        MainWindow.setTabOrder(self.lineEditNoRek1, self.lineEditNm2)
        MainWindow.setTabOrder(self.lineEditNm2, self.lineEditAlamat2)
        MainWindow.setTabOrder(self.lineEditAlamat2, self.lineEditTelp2)
        MainWindow.setTabOrder(self.lineEditTelp2, self.lineEditNoRek2)
        MainWindow.setTabOrder(self.lineEditNoRek2, self.comboBoxListPrinter)
        MainWindow.setTabOrder(self.comboBoxListPrinter, self.pushButtonSimpanInformasi)
        MainWindow.setTabOrder(self.pushButtonSimpanInformasi, self.dateEditTglSetor)
        MainWindow.setTabOrder(self.dateEditTglSetor, self.lineEditCari)
        MainWindow.setTabOrder(self.lineEditCari, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.pushButtonRefresh)
        MainWindow.setTabOrder(self.pushButtonRefresh, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.lineEditID)
        MainWindow.setTabOrder(self.lineEditID, self.lineEditTerbilang)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBoxTunai.setTitle(_translate("MainWindow", "Setoran Tunai", None))
        self.label_20.setText(_translate("MainWindow", "Uang Kertas", None))
        self.label_86.setText(_translate("MainWindow", "Identitas Tas", None))
        self.label_75.setText(_translate("MainWindow", "500", None))
        self.label_23.setText(_translate("MainWindow", "100.000", None))
        self.label_85.setText(_translate("MainWindow", "STICKER", None))
        self.label_74.setText(_translate("MainWindow", "1.000", None))
        self.label_76.setText(_translate("MainWindow", "200", None))
        self.label_67.setText(_translate("MainWindow", "50.000", None))
        self.label_68.setText(_translate("MainWindow", "20.000", None))
        self.label_82.setText(_translate("MainWindow", "GRAND TOTAL :", None))
        self.label_69.setText(_translate("MainWindow", "10.000", None))
        self.label_70.setText(_translate("MainWindow", "5.000", None))
        self.label_73.setText(_translate("MainWindow", "TOTAL", None))
        self.label_72.setText(_translate("MainWindow", "1.000", None))
        self.label_71.setText(_translate("MainWindow", "2.000", None))
        self.label_77.setText(_translate("MainWindow", "100", None))
        self.label_78.setText(_translate("MainWindow", "50", None))
        self.label_79.setText(_translate("MainWindow", "25", None))
        self.label_81.setText(_translate("MainWindow", "TOTAL", None))
        self.label_80.setText(_translate("MainWindow", "Uang Logam", None))
        self.label_83.setText(_translate("MainWindow", "TAS", None))
        self.label_84.setText(_translate("MainWindow", "SEGEL TAS", None))
        self.label_87.setText(_translate("MainWindow", "CATATAN", None))
        self.groupBoxGiro.setTitle(_translate("MainWindow", "Setoran Giro", None))
        self.label_31.setText(_translate("MainWindow", "Berita / Keterangan :", None))
        self.label_35.setText(_translate("MainWindow", "Tanggal Jatuh Tempo :", None))
        self.groupBoxGiroBanyak.setTitle(_translate("MainWindow", "Khusus Setoran >= 100.000 (ekivalen)", None))
        self.labelSumberDana.setText(_translate("MainWindow", "Tulis Sumber Dana :", None))
        self.label_36.setText(_translate("MainWindow", "Pilih Sumber Dana :", None))
        self.labelTujuanTransaksi.setText(_translate("MainWindow", "Tulis Tujuan Transaksi :", None))
        self.label_38.setText(_translate("MainWindow", "Pilih Tujuan Transaksi :", None))
        self.comboBoxTujuanTrans.setItemText(0, _translate("MainWindow", "Rekening Pusat", None))
        self.comboBoxTujuanTrans.setItemText(1, _translate("MainWindow", "(diisi sendiri)", None))
        self.comboBoxSumberDana.setItemText(0, _translate("MainWindow", "Penjualan Rokok", None))
        self.comboBoxSumberDana.setItemText(1, _translate("MainWindow", "(diisi sendiri)", None))
        self.label_33.setText(_translate("MainWindow", "Nomor Giro :", None))
        self.label_34.setText(_translate("MainWindow", "Kota :", None))
        self.label_32.setText(_translate("MainWindow", "Kode Bank :", None))
        self.label_16.setText(_translate("MainWindow", "Pilih Penyetor :", None))
        self.pushButtonSimpan.setText(_translate("MainWindow", "Simpan", None))
        self.pushButtonCetak.setText(_translate("MainWindow", "Cetak", None))
        self.pushButtonBatal.setText(_translate("MainWindow", "Batal", None))
        self.label_7.setText(_translate("MainWindow", "ID", None))
        self.label_17.setText(_translate("MainWindow", "Masukkan Jumlah :", None))
        self.comboBoxJenisSetoran.setItemText(0, _translate("MainWindow", "Setor Tunai", None))
        self.comboBoxJenisSetoran.setItemText(1, _translate("MainWindow", "Setor Giro", None))
        self.label_18.setText(_translate("MainWindow", "Pilih Jenis Setoran :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Slip Setoran", None))
        self.label_3.setText(_translate("MainWindow", "Cari ", None))
        self.tableWidget.setSortingEnabled(False)
        self.pushButtonRefresh.setText(_translate("MainWindow", "Refresh", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Data", None))
        self.label.setText(_translate("MainWindow", "No. Rekening untuk Giro :", None))
        self.label_2.setText(_translate("MainWindow", "Nama Pemilik Rekening :", None))
        self.label_22.setText(_translate("MainWindow", "No. Rekening untuk Pelunasan :", None))
        self.label_21.setText(_translate("MainWindow", "No. Rekening untuk Penjualan :", None))
        self.label_4.setText(_translate("MainWindow", "Pilih Printer :", None))
        self.label_5.setText(_translate("MainWindow", "No. Rekening Pemilik :", None))
        self.label_11.setText(_translate("MainWindow", "Telepon :", None))
        self.label_13.setText(_translate("MainWindow", "No. Rekening :", None))
        self.label_12.setText(_translate("MainWindow", "Alamat Penyetor :", None))
        self.label_10.setText(_translate("MainWindow", "Nama Penyetor :", None))
        self.label_14.setText(_translate("MainWindow", "Penyetor Utama", None))
        self.label_25.setText(_translate("MainWindow", "Telepon :", None))
        self.label_30.setText(_translate("MainWindow", "Penyetor Alternatif", None))
        self.label_26.setText(_translate("MainWindow", "No. Rekening :", None))
        self.label_29.setText(_translate("MainWindow", "Nama Penyetor :", None))
        self.label_15.setText(_translate("MainWindow", "Alamat Penyetor :", None))
        self.pushButtonSimpanInformasi.setText(_translate("MainWindow", "SIMPAN", None))
        self.label_6.setText(_translate("MainWindow", "Alamat Pemilik :", None))
        self.label_8.setText(_translate("MainWindow", "Telp. Pemilik :", None))
        self.label_65.setText(_translate("MainWindow", "Pengambil Uang Tunai :", None))
        self.label_66.setText(_translate("MainWindow", "Alamat Pengambil Uang Tunai :", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Informasi", None))

import icon_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

